
platform :ios, '10.3'

target 'wanghouyusheng' do
  pod 'pop', '~>1.0.12'
  pod 'Masonry', '~>1.1.0'
  pod 'BaiduMobStatCodeless' , '~> 4.9.5'
  pod 'SDWebImage'
  pod 'SKGuideView'
  pod 'UMCCommon'
  pod 'UMCAnalytics'
  pod 'RITLPhotos'
  pod 'YYWebImage'
  pod 'BmobSDK', '~>2.4.1'
  pod 'AFNetworking'
  pod 'AliyunOSSiOS'
  pod 'SVProgressHUD', '~>2.2.5'
  pod 'CWLateralSlide', '~> 1.6.3'

end
